### ISSUE TITLE
Insert new file into highlighted directory

### ISSUE THREAD

**Issue by sgwill** [david-driscoll/atom-yeoman#9]
Currently atom-yeoman adds new files (new Class, new Controller, etc) into the project root instead of the currently highlighted folder.

Instead, add to highlighted folder

**Comment by david-driscoll** [comment]
Begs the question, should we always ask for the directory they want to work out of?

* Selected
* Project A
* Project B

**Comment by sgwill** [comment]
Yeah, I think that's how I'll start the feature and try using it for a few days to see if it feels right.

**Comment by blai** [comment]
I'd say this should be a preference. I see both case (add new files into root, and add new files into highlighted folder) valid.

Maybe it can be a option?

**Comment by david-driscoll** [comment]
Make a checkbox, to try and use the selected folder first, or a set of options perhaps.

**Comment by david-driscoll** [comment]
This will be going shortly with some caveats in how yeoman works (namely if .yo-rc.json exists or not).  This can be fixed via something like https://github.com/OmniSharp/generator-aspnet/issues/159 .
